# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0003_auto_20160914_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
