# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0004_auto_20160917_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
