# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0007_auto_20161002_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='likes',
            new_name='tweet',
        ),
    ]
