# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0009_auto_20161002_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='person',
            field=models.ManyToManyField(related_name='person', to=settings.AUTH_USER_MODEL),
        ),
    ]
