# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0019_auto_20161025_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter_app.UserProfile'),
        ),
    ]
